---
- name: Ensure ~/.bash_aliases is sourced in ~/.bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi"
    state: present

- name: Deploy .tmux.conf configuration file
  ansible.builtin.copy:
    src: .tmux.conf
    dest: ~/.tmux.conf
    mode: '0644'
