---
- name: Download Docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Run Docker install script
  ansible.builtin.command:
    cmd: /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Ensure user is in docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

- name: Ensure docker-compose plugin directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins"
    state: directory
    mode: '0755'
  become: no

- name: Download docker-compose plugin
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-linux-x86_64"
    dest: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose"
    mode: '0755'
  become: no
